name = "ParticleCorrelations"
uuid = "2bdc0d93-21f3-4e16-a26e-769a2eaf80d4"
authors = ["Artur Gower", "Aristeidis Karnezis"]
version = "0.0.1"

[deps]
ClassicalOrthogonalPolynomials = "b30e2e7b-c4ee-47da-9d5f-2c5c27239acd"
HCubature = "19dc6840-f33b-545b-b366-655c7e3ffd49"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MultipleScattering = "80a8ab25-5750-5d93-a6d7-4adc97cdd5fb"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
ClassicalOrthogonalPolynomials = "0, 0.11"
MultipleScattering = "^0.1"
HCubature = "1"
Reexport = "0.2, 1.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
